# Generated by Django 2.0 on 2018-08-21 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid number', regex='\\d{10}')])),
                ('password', models.CharField(max_length=50)),
                ('agent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('image', models.FileField(upload_to='', validators=[myapp.models.validate_file_extension])),
                ('discription', models.TextField(max_length=1000)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Myuser')),
            ],
        ),
    ]
