# Generated by Django 2.0 on 2018-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
